version: '3'
 
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - db-variables.env
    networks:
      - backend
  gabsite:
    depends_on:
      - mysql
    image: gabsite
    container_name: gabsite
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - web-variables.env
    volumes:
      - ./www:/var/www/site
    links:
      - mysql:mysql
    restart: always
    networks:
      - backend
 
networks:
  backend:
    driver: bridge

volumes:
  www:
  database.sql:
  my-datavolume: